### ISSUE TITLE
Create Staging VMS

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#11]
- [x] Two Staging VMs
- [x] machine names allsearch-staging1,2
- [x] Machine Specs: 40GB local disk space, 16GB RAM, and 2 cpus
- [x] Public Domain name: allsearch-staging.princeton.edu

**Comment by acozine** [comment]
We're assuming the following network rules:
SSH open to the VPN
HTTP/S open to libnet
If we need to add anything to that list, please let us know.

**Comment by acozine** [comment]
VMs are ready to use. Disk size is 30GB, which is the default for the new Jammy boxes, instead of 40GB. If you need more, just let me know. PR to the princeton_ansible inventory coming soon.
