### ISSUE TITLE
Adjust Colors/Spacing of Tray Results and Call Number Values

### ISSUE THREAD

**Issue by kelea99** [pulibrary/allsearch_frontend#127]
### Current display
In the current display you lose sight of the call numbers/ locations of the items in the search resulsts.
![super cramped metadata is on top of one another - hard to read](https://github.com/pulibrary/orangelight/assets/45043014/9d468001-26d8-4ea3-9147-739b8341f221)

### Desired display
As a UX stakeholder, I would like the spacing between the call number and next search result (and the alternating colors of the search results) to display like that of the current Bento search results (see screenshot 2).
![much better spacing between metadata sections](https://github.com/pulibrary/orangelight/assets/45043014/2bc66ef4-e38d-4881-818b-c921e7a35823)

### Acceptance criteria

- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] the spacing between the call number/location and next search result has the same amount of spacing as that of production bento.
- [ ] The search results have alternating colors like that of production bento

### Notes
This was from weekly feedback from UX colleagues.

**Comment by kevinreiss** [comment]
A little bit confused by the ticket. Are we talking about adding the stackmap links?

**Comment by kevinreiss** [comment]
Need to clarify if we are talking about the "<<" arrow spacing btw the location call number or about adding the stackmap feature like we have in the actual catalog.

**Comment by kevinreiss** [comment]
This is about whether or not we want to stackmap to the all search display.

**Comment by christinach** [comment]
My understanding is that in the new all_search we decided to use a numbered list (1,2,3) instead of alternating the color. We've also added a line to indicate a border between the results. I don't think it's necessary to go back to the old all search display.

**Comment by christinach** [comment]
@kelea99 signs off on the column spacing and will confirm with AUX on the colors.

**Comment by kelea99** [comment]
Answering this for colors as well. Its fine as is. We can reassess when we know the styling from WDS. @christinach and @kevinreiss  , may i close the ticket?

**Comment by christinach** [comment]
Yes @kelea99 we can close it.
