### ISSUE TITLE
Truncate the description metadata fields

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/allsearch_frontend#128]
### Current display

The library archives tray here is extremely huge, because it includes so much description text: https://allsearch-staging.princeton.edu/?q=fish

### Desired display

The description is truncated.

### Acceptance criteria

- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [x] Long descriptions are truncated, to the same length as what is in current prod (150 characters)
- [x] It doesn't truncate in the middle of a word
- [x] When a description has been truncated, there is an ellipsis (...) to let the user know that it has been truncated

### Notes
* discovery_utils is currently truncating long descriptions.  Maybe we can re-use that setting here?
* We liked Franklin's truncation, which keeps the first 2-3 sentences: https://franklin.library.upenn.edu/bento?q=cat#gsc.tab=0&gsc.q=cat&gsc.page=1

**Comment by kelea99** [comment]
Going to hand this over to UX folks to keep tabs on. this is something that would benefit from user research before work and implementation.
