### ISSUE TITLE
Make underline below titles of search results turn orange on hover.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/allsearch_frontend#132]
### Current display
The display does not have any visual indication of the item being hovered over, other than a hand appearing vs the arrow.  
![no hover action on title](https://github.com/pulibrary/allsearch_frontend/assets/45043014/21054c11-3bbc-49e9-abea-40a96f18fe9e)

### Desired display
As a UX stakeholder, I would like the underline under the title to turn orange when hovered over, like that of the current Bento search results (see screenshot 2).
![line turns orange with hover](https://github.com/pulibrary/allsearch_frontend/assets/45043014/aa8d3a01-8178-4345-bd21-92938832d9c9)

### Acceptance criteria

- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [x] line under title turns orange when hovered over

### Notes
from @kelea99 : the thickness of that line should be tested. User feeback from Figgy's lines around active boxes within order manager also turn orange, but the thinness of them was a pain point for users. they wanted them slightly thicker and more obvious. Something to take with UX about?

**Comment by sandbergja** [comment]
We should also make this change happen on focus (i.e. when a user tabs to the title link).  This is not currently happening in prod.
