### ISSUE TITLE
Position Best Bets Above main Search Results. 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#187]
### Current display
When a match to the query is found the "Best Bet" tray is currently rendered at the top of the third column (in large-screen view). 
<img width="1742" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBellKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f69e5483fa1ba98a6bc6d765405ef34438ae673/Screenshot%202024-01-29%20at%209.31.23%E2%80%AFAM.png" alt="Current all search best bets result example for 'New York Times' query" />

### Desired display
Display best bets in a region above the main search results but below the search box. This is what the current interface does.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4ac06c70a2d6a84f4b0e43b67b38cfeb635b435/Screenshot%202024-01-29%20at%209.31.46%E2%80%AFAM.png" alt="Current production best bet result example for 'New York Times' query" />

### Acceptance criteria

- [ ] Update wireframe to include placememt of best bet region
- [ ] Best bets are displayed in a region btw the main search results and the search box in full screen views.
- [ ] Best bets are displayed at the top of the list search results in small screen views. 
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
  - axe dev tools
  - Lighthouse
  - Wave

## Proposed Wireframe
<img width="923" alt="Screenshot 2024-03-12 at 4 00 54 PM" src="https://github.com/pulibrary/allsearch_frontend/assets/9905193/9eb9ff4e-8ec7-445d-a709-78134570e69f" alt="New position of best bets">

**Comment by sandbergja** [comment]
@kevinreiss is going to ask stakeholders about this one.

**Comment by kevinreiss** [comment]
Feedback from public services librarians:

****
I like the third column positioning. As long as it remains somewhere at the top I'm good


*****
You're talking about where the "best bet" result appears? I just asked two Info Desk students, one undergrad one grad - they both said they preferred the current placement. (though I notice that the yellow highlight color sort of blinks and then goes off - I feel like that used to stay highlighted, which I think is a good feature...)  In the "new" example, they both said they don't tend to look thoroughly at the boxes  :thinking_face:  so maybe if best bets was on the left column, that would help?

**Comment by christinach** [comment]
We are not changing the Best Bets position until further UX testing and feedback from stakeholders.

**Comment by kevinreiss** [comment]
Try to implement this before user testing per AUX discussion 3/7.

**Comment by sandbergja** [comment]
Rationale: we want to group similar things together.  Taking best bets out of the grid makes it look like it's a different type of thing than the grid.

**Comment by rladdusaw** [comment]
WIP branch at https://github.com/pulibrary/allsearch_frontend/tree/187-move-best-bets
