### ISSUE TITLE
Add Individual Tray Descriptions

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#197]
### Current display
We have lorum ipsum text for the bento tray description displayed below the title of each individual display. 

### Desired display
Each tray should be described with a useful and clear phrase. 

### Acceptance criteria

- [ ] Each Tray has a description. Use these [strings](https://docs.google.com/spreadsheets/d/1xfLcHPxfPBMOaznmbfUPK0taSSQZf-iGh-2oNck52ms/edit#gid=0) as our starting place. 
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Notes
Need to consult with AUX, when we discussed this last summer they were going to provide descriptions.

**Comment by kevinreiss** [comment]
AUX Team can provide starting recommendations for this text, roughly in the next two weeks if possible.

**Comment by beth-german** [comment]
Drafting descriptions here, will note when finished: https://docs.google.com/spreadsheets/d/1xfLcHPxfPBMOaznmbfUPK0taSSQZf-iGh-2oNck52ms/edit#gid=0
