### ISSUE TITLE
Create Production VMs

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#2]
- [x] Two Production VMs
- [x] machine names allsearch-prod1,2
- [x] Machine Specs: 40GB local disk space, 16GB RAM, and 2 cpus
- [x] Public Domain name: allsearch.princeton.edu

**Comment by acozine** [comment]
VMs are ready to use. Disk size is 30GB, which is the default for the new Jammy boxes, instead of 40GB. If you need more, just let me know. #4338 took care of the inventory piece. To add these to the load-balancer, create the certs and then merge #4339.
