### ISSUE TITLE
[Desktop View] Skip to section and search form

### ISSUE THREAD

**Issue by christinach** [pulibrary/allsearch_frontend#227]
Update skip to section following the:
[Draft](https://docs.google.com/document/d/1ZuzfqSD2GtQdC8wWiZP7qVqU4NfMYqUaZyoLZEQjVgg/edit)

![screenshot from Draft document showing search form and skip to section links](https://github.com/pulibrary/allsearch_frontend/assets/9905193/3c577b5c-9397-4b11-8f75-24e6f9b85c92)

Fixed display
Desktop
- [x] search box 
- [x] skip to section links.

**Comment by kevinreiss** [comment]
Discussing adding a mobile wireframe on 6/21.
