### ISSUE TITLE
[Vue warn]: Failed to resolve component: search

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/allsearch_frontend#232]
Console warning:

```
Vue warn]: Failed to resolve component: search
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <SearchBar position="centered" > 
  at <InitialSearch> 
  at <App>
```

Creates mental overhead and seems like a simple fix.

**Comment by sandbergja** [comment]
I've been wondering about this one.  `<search>` [is a valid HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search), maybe Vue just doesn't know about it yet?
