### ISSUE TITLE
Console error: Deprecated feature used

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/allsearch_frontend#233]
Console error: Deprecated feature used

"The page may stop working in an upcoming version of Chrome"

```
Deprecated feature used
1 source
onloadwff.js:71
```

**Comment by sandbergja** [comment]
I'm unable to reproduce this.  Could it be related to the [lastpass chrome extension](https://github.com/lastpass/lastpass-cli/issues/428)?

**Comment by maxkadel** [comment]
Looks like that's it, @sandbergja  - I checked in an incognito window and it's not there. Thanks!
