### ISSUE TITLE
Update Null Results Language in Trays

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#279]
### Current display
AUX will provide the text. 

### Acceptance criteria

- [x] Use the format: 
         - No results matched your search.    
         - Try changing your search terms or searching the [Insert Tray Name Here]" for all Trays when there is null results. 
- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

**Comment by kevinreiss** [comment]
@Ka-YT assigning you to update the ticket with a reference to new phrasing we should use for null results per our discussion today.

**Comment by beth-german** [comment]
@Ka-YT https://allsearch.princeton.edu/?q=adsfhsdfjhajdkfkjdajf%3Bkjldasfjk .... Current format is "No results found. Search the [link to tray target]." Ex. No results found. Search the Library Databases. .... This seems okay for MVP, do you have any edits?

**Comment by beth-german** [comment]
Ack! Sorry, if you're looking for the spreadsheet I referenced in the check-in, it doesn't exist. That was my mistake. We'll get the final rec this week.

**Comment by kevinreiss** [comment]
Checked in on 7/8 for an update.

**Comment by beth-german** [comment]
Recommendation: "No results matched your search. <br> Try changing your search terms or searching the [target]."

**Comment by beth-german** [comment]
![image](https://github.com/pulibrary/allsearch_frontend/assets/38568051/e4d2f8dc-9c4e-41fd-a1d1-18758eb68f98)
