### ISSUE TITLE
Secrets Management

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#28]
Research secure ways to manage secrets in vue.js. 

- Idea: and an endpoint to the all search api that accepts errors from the front-end application and sends them off to Honeybadger. 

### Concrete example

1. Check out the [honeybadger branch](https://github.com/pulibrary/allsearch_frontend/tree/honeybadger)
2. `yarn dev`
3. Open your network tab in your browser devtools
4. Go to the URL that `yarn dev` mentioned
5. In the Network tab, note that there is a POST request going to https://api.honeybadger.io/v1/notices/js.  Open it
6. Note that the request has an `X-API-Key` containing the key specified in our .env file.
7. Open the Sources (Chrome) or Debugger (Firefox) tab
8. Search all files for "VITE_HONEYBADGER_API_KEY"
9. Note that one of the files spills the beans!  Showing the secret to any user that cares to investigate.

**Comment by maxkadel** [comment]
- More details on [environment variables in Vite](https://vitejs.dev/guide/env-and-mode.html)
  - "To prevent accidentally leaking env variables to the client, only variables prefixed with `VITE_` are exposed to your Vite-processed code."
- [dotenv package](https://github.com/motdotla/dotenv) (supposedly already used for Vite, but I don't see it in our package.json or yarn.lock)

**Comment by maxkadel** [comment]
This is for react, but seems like it could work similarly here - a very small-scale backend server that would have access to the keys, and requests to protected apis would go through the backend, rather than directly from the browser.

**Comment by maxkadel** [comment]
When I deploy the [honeybadger_secret_test](https://github.com/pulibrary/allsearch_frontend/tree/honeybadger_secret_test) branch to [allsearch-staging](https://allsearch-staging.princeton.edu/), I can see the Honeybadger key in the POST request that is sent to honeybadger. 

When I go to the filesystem, I cannot see the `VITE_HONEYBADGER_API_KEY`, or the `SUPER_SECRET_KEY` I put in the `.env` file via Ansible / Capistrano. If the front-end sends any requests using those keys, though, they will be visible.
