### ISSUE TITLE
Create Basic Wireframe for Large Screen General All Search Layout

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#29]
- [x] Placeholder for Library Header
- [x] Search Box (the query from the current search should be displayed in the searchbox
- [x] ~Page Header is Search All~ - see below for conflicting header info
- [x] Add a label, similar to mobile, to skip to section for the menu 
- [x] Take off the number of results from the menu options
- [x] Three Columns of results (on large screens)
- [x] Add borders around the trays 
- [x] Best bets move to the top of the third column (rendered only when there is a match)
- [x] Placeholder for Library Footer 
- [x] Use "Search for Library Materials and Website Content" as the page header (i.e. the h1 value). 

AUX Recommendations https://docs.google.com/document/d/1qbYeksYle71LWDbcQYGJnByWeupf9yEEkfSxvGj3Zl8/edit 
Wireframe exercise with AUX: https://docs.google.com/presentation/d/17MRmAckZDMXDVsVggZoU6SgRnforpwzyggLcjRtAdDw/edit#slide=id.g28080f467ef_0_10

**Comment by sandbergja** [comment]
XD wireframe is here: https://xd.adobe.com/view/5d82af9c-e5ec-43b4-83ab-87a317989a63-08d1/
