### ISSUE TITLE
Create Basic Wireframe for Catalog Tray

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#30]
Reflect the following changes from the current interface

- [x] Reduce results to 3 
- [x] Add borders around the tray
- [x] Result positions should be numbered 
- [x] Unlink the header (now just a label). Add a call to action (i.e. a link) to the source interface right aligned at the same level of the header marked "Refine Your Search". 
- [x] Include a placeholder description of the tray (AUX will provide description recommendations)
~~- [ ] Call to see all results next to the header~~  See 4th checkbox with 'Refine your search'
- [x] Add a link that is a call action that displays the total number of search results reported by the API with the label "see {number of results} results" for the query in the source interface at the bottom of a tray 
- [x] Should retain the same metadata values displayed in the current interface.
        * Title
        * Format
        * Author
        * Publication Statement/Year
        * Holding location statement
- [x] Should display an online link to the resource (if present)

**Comment by christinach** [comment]
see [wireframe](https://www.figma.com/file/4WURb632luvlLxBaiJPN4d/mobile---search-results%2F-Tray?type=design&node-id=0%3A1&mode=design&t=9DxmfOAKQY8uB00V-1)
