### ISSUE TITLE
Add Icon Set to Project

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#31]
We use the same icon set in the current Library website and Orangelight. We should keep using these in the new project. 

### Implementation Notes
Check here: https://drive.google.com/drive/folders/0B7lJwwFLye5XaTNzdFAwRTEyNlk?resourcekey=0-x2ecoBlnijns94wO0Qhm4A

**Comment by maxkadel** [comment]
Put in `public/assets/fonts/icons/`
