### ISSUE TITLE
Add 'Skip to Section' for Bento Search Result Options

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#32]
Wait to implement this until all the individuals trays are completed.

- [ ] Always displays a label "skip to section" regardless of screen size
- [ ] Displays the labels of each tray on the page (i.e. Catalog, Articles, Finding Aids..etc.)
- [ ] Does NOT display the result count in each option. 
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

**Comment by maxkadel** [comment]
@sandbergja had question - how does this relate to other "skip to [x]" links? Would it be possible to have all of them visible (an accessibility best practice) and all together? 

@sandbergja and @christinach will create alternate wireframes for desktop and mobile to show what it might look like.

**Comment by sandbergja** [comment]
I can't think of a good way to present all of these links together at the top of the page, and couldn't find any good examples with this type of extensive skip nav visible at the top of the page.

**Comment by kevinreiss** [comment]
I think we do need to provide a way to jump through the options to users, can we return to doing this above the search results after the form?

**Comment by sandbergja** [comment]
Seems good to me.
