### ISSUE TITLE
[Dark or System Default Android/Iphone mobile] Tray contents besides the title are not visible

### ISSUE THREAD

**Issue by christinach** [pulibrary/allsearch_frontend#344]
### Expected behavior
I want to be able to view the all search website on my mobile when I switch in between different themes.

### Actual behavior
Chrome settings when I select Dark mode or System Default, I can only see the Tray title not the tray details.

### Steps to replicate
In an Android or Iphone mobile go to chrome settings and select 'dark' theme or 'system default'
go to https://allsearch.princeton.edu/?q=cat

### Impact of this bug
E.g. "I can't work until this is fixed" or "I have a workaround"

### Screenshots
![allsearch results first screenshot](https://github.com/pulibrary/allsearch_frontend/assets/9905193/46452b8d-7237-4014-a760-9734b096ab80)
![allsearch results second screenshot](https://github.com/pulibrary/allsearch_frontend/assets/9905193/39729cdc-5395-47f7-8624-dfd3fc6ff1ec)

**Comment by sandbergja** [comment]
The rspec tests currently fail if you set your OS settings to dark mode.  The success criteria for this one will be to make sure that these tests don't fail when the OS is set to dark mode.

**Comment by winsice-ng** [comment]
We decided in conjunction with the AUX team to focus on meeting the accessibility requirements for dark mode. As a result, we added media queries related to dark mode such as changing text color for links and changing background colors. Additionally, we decided that future changes to the design in dark mode will be in a future ticket. 🍄 🍿 🌺
