### ISSUE TITLE
Create Wireframe for Mobile General Page Layout

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#38]
- [x] Placeholder for Library Header
- [x] Page Header is 'Search results from something'
- [x] Search Box (the query from the current search should be displayed in the searchbox
- [x] Add a label, similar to mobile, to skip to section for the menu 
- [x] Take off the number of results from the menu options
- [x] Add borders around the trays 
~~- [ ] Best bets move to the top of the third column (rendered only when there is a match)~~ not a mobile view
- [x] Placeholder for Library Footer 
- [x] Use "Search for Library Materials and Website Content" as the page header (i.e. the h1 value). 

AUX Recommendations https://docs.google.com/document/d/1qbYeksYle71LWDbcQYGJnByWeupf9yEEkfSxvGj3Zl8/edit 
Wireframe exercise with AUX: https://docs.google.com/presentation/d/17MRmAckZDMXDVsVggZoU6SgRnforpwzyggLcjRtAdDw/edit#slide=id.g28080f467ef_0_10

**Comment by christinach** [comment]
Link to the [mobile wireframe](https://www.figma.com/file/4WURb632luvlLxBaiJPN4d/mobile---search-results?type=design&node-id=0%3A1&mode=design&t=cucVLB4MmjCyg8sY-1)
