### ISSUE TITLE
Show or hide a banner based on allsearch_api response

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/allsearch_frontend#385]
### User story
As a library administrator, I sometimes want to prominently display temporary messages to users. 

### Acceptance criteria
- [ ] Uses the data from the allsearch-api for:
   - [ ] the banner text (default none)
   - [ ] the alert status (valid options: [warning, error, success, info]) (default: info)
   - [ ] whether or not the alert should be dismissible (default: true)
   - [ ] whether or not the alert should autoclear (default: false)
- [ ] Uses the data from the allsearch-api to show or hide the component (default: hide)
- [ ] Displays html from the allsearch-api response, including headers and links
- [ ] Use the Lux alert component
- [ ] Check for link display contrast (must be accessible)
- [ ] Check for display in dark mode (should be the same display in light or dark mode)
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Concrete example
During the soft launch of the website, we want to solicit feedback from users, and to do so using a banner that includes a header and a link to a survey.

### Implementation notes, if any
See https://github.com/pulibrary/allsearch_api/issues/265 for allsearch-api implementation.

**Comment by maxkadel** [comment]
Format of api response

```json
{
  "banner_text":"\u003ch2\u003eThis is a big heading about an important thing\u003c/h2\u003e\u003cp\u003eIt includes a \u003ca href=\"https://www.example.com\"\u003elink\u003c/a\u003e\u003c/p\u003e",
  "display_banner":false,
  "alert_status":"info",
  "dismissable":true,
  "autoclear":false
}
```

**Comment by rladdusaw** [comment]
Should we use dismissible instead of dismissable? I'm getting an spelling autocorrect error.

**Comment by maxkadel** [comment]
Yes, let's use dismissible - corrected
