### ISSUE TITLE
Create Mock Implementation of Data Service

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#40]
Used for development purposes. 

Returns a static set of search results as a standin for the backend api. 

The service should have a method that accepts the search type (catalog, articles+, etc) and the search query string that returns an example search results object. This can be used for development without blocking us with needing the full service implementation.

**Comment by maxkadel** [comment]
Can interfile tests with code in same directory. Confirm that all tests are running in CI.
