### ISSUE TITLE
Add a meaningful page title

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/allsearch_frontend#50]
### Steps to recreate

Use the WAVE browser extension

### URL

https://allsearch-staging.princeton.edu/

### Issues

WCAG 2.4.2: [Page titled](https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html)

### Severity

Fix before MVP

### WCAG Conformance level (A, AA, AAA)

Level A

### User impact

- Users can't distinguish between multiple tabs/windows they have open

### Recommended fix

Add a title element to the HTML head element, with unique information at the front. 

Use the form: "walrus search results | Princeton University Library", in case the user has multiple allsearch tabs open.

### Acceptance criteria

- [ ] I can successfully hear the title with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
  - axe dev tools
  - Lighthouse
  - Wave

### Notes

* See [the Understanding Page Titled documentation](https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html) for more information

**Comment by kevinreiss** [comment]
Why would this form ""walrus search results | Princeton University Library" be better for users with multiple tabs?

**Comment by sandbergja** [comment]
Ah, I was just thinking of the cases where users have tons of tabs open, and the page title is truncated.  Then, they could know which tab is their "walrus" search vs. their "penguins" search.
