### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/allsearch_frontend#73]
### User story
Favicons are useful in differentiating tabs in a user's browser, and make a site look more professional. 

Also, when we don't have one, there's a 404 error in the console when the page tries to load it. 
![image](https://github.com/pulibrary/allsearch_frontend/assets/45948126/3935f880-7676-4024-9c00-939e2ff1bb84)

### Acceptance criteria
- [ ] There is a Princeton Libraries branded favicon that displays in the tab in the browser
- [ ] The console does not report a 404 error regarding the favicon when loading the page

### Concrete example
Example [image file from Orangelight](https://github.com/pulibrary/orangelight/blob/main/app/assets/images/favicon.ico) 

### Implementation notes, if any
- Is there a Library-specific branding page?
- Communications has a [Logo and Graphic Identity page](https://communications.princeton.edu/guides-tools/logo-graphic-identity) that includes colors

**Comment by kevinreiss** [comment]
We can use the favicon files from the library website. We don't really have a library specific branding page with any usable info, see https://library.princeton.edu/princeton-university-library-logos.
